SIMULATION:
  START: 21600
  END: 36000
  STEP_TIME: 20
  TIME2FINISH: 0

REQUEST:
  DATA:
    TRAIN: './data/train'
    VALIDATION: './data/validation'
    TEST: './data/test'
  SAMPLE_RATE: 0.15
  CHECK_ITINERARY: False
  CONSTRAINTS:
    max_assign_time: 600
    max_pickup_time: 600
    max_travel_time_mul: 1.5
    max_travel_dis_mul: 1.5
  BEHAVIORS:
    max_assign_time: 180
    max_pickup_time: 300
    cancel_prob_assign: 0.6
    cancel_prob_pickup: 0.1
    max_tol_vehicle_capacity: 4
    max_tol_price: None

VEHICLE:
  DATA: './data/driver_distribution.csv'
  NUM: 500
  VELOCITY: 6.
  MAXCAPACITY: 2
  PlanPathMethod: 'NearestFirst'
  REPOSITION:
    TYPE: True
    METHOD: 'Random'
    
ENVIRONMENT:
  TYPE: 'NY'
  NY:
    RoadFile: './data/graph.graphml'
    TravelTimeFile: None
    TravelDisFile: None
    X_GRID_NUM: 10
    Y_GRID_NUM: 10
  TOY:
    NumNode: 21
    DisPerLine: 500
  CONSIDER_ITINERARY: False
  CONSIDER_CONGESTION: False

MODEL:
  EPISODES: 500
  LOCATION_EMBED_NUM: 20
  TIME_EMBED_NUM: 10
  DISCOUNT_FACTOR: 0.99
  LEARNING_RATE: 0.01
  BATCH_SIZE: 128
  MEMORY_SIZE: 20000
  TRAIN_FREQUENCY: 50
  TIME_INTERVAL: 900
  REPOSITION: False